### ISSUE TITLE
Update RLT Loot Tracker Google Sheet for each new RLT release

### ISSUE THREAD

**Issue by MemeticsX** [MemeticsX/RLT#22]
Update RLT Loot Tracker Google Sheet for each new release:

- [x] 0.15.4 (beta) for MC 1.19.3
- [ ] 0.15.4 for MC 1.19.3 (if no new issues found in beta)
- [ ] [TBD] for MC 1.20
